-- NPCs de Kirigakure (mybb_sg_sg_npcs)
-- Líderes de clan de Kiri. afiliacion = 'Kiri' inline (no toca a NPCs de otras aldeas).
-- Los stats quedan con sus valores por defecto.

INSERT INTO `mybb_sg_sg_npcs` (`codigo`, `nombre`, `clan_grupo`, `afiliacion`, `cargo`, `frase`, `edad`, `descripcion`, `rango`, `nivel`) VALUES
('renjiro-funato', 'Renjiro Funato', 'Funato', 'Kiri', 'Líder del Clan Funato – Primer Mizukage', '“El mar no perdona a los débiles, pero recompensa a los que resisten.”', '52', 'Renjiro Funato es el actual comandante de las defensas marítimas de Kirigakure y uno de los líderes más experimentados de la aldea. Nació en una generación marcada por tormentas constantes y rutas comerciales cada vez más peligrosas. Desde joven fue entrenado en navegación y combate naval, aprendiendo que la supervivencia de Kiri depende del control del mar. Durante su juventud, lideró misiones de rescate en medio de tifones que destruyeron embarcaciones y asentamientos costeros. Estas experiencias lo convirtieron en un estratega prudente, capaz de evaluar riesgos antes de actuar. Su reputación creció rápidamente, y fue elegido líder tras la muerte de su predecesor en una expedición fallida. Como líder actual, Renjiro supervisa todas las flotas de patrulla y mantiene sistemas de alerta temprana contra amenazas marinas. También ha promovido la construcción de puertos fortificados y refugios costeros para proteger a la población. Renjiro cree que la guerra no es el mayor peligro para Kirigakure; el verdadero enemigo es la negligencia. Su liderazgo se basa en la preparación constante y la responsabilidad colectiva.', 'Kage', 20),
('daizen-hoshigaki', 'Daizen Hoshigaki', 'Hoshigaki', 'Kiri', 'Líder del Clan Hoshigaki – Consejero del Mizukage', '“El océano revela la verdad de quien se atreve a enfrentarlo.”', '47', 'Daizen Hoshigaki es conocido por su presencia imponente y su disciplina férrea. Nació en una familia de guerreros anfibios y desde niño mostró una resistencia física excepcional. Su entrenamiento incluyó largas inmersiones en aguas profundas y combates prolongados en condiciones extremas. Durante una crisis provocada por criaturas marinas, Daizen lideró un grupo de guerreros que defendió un puerto estratégico durante tres días sin descanso. Este acto lo convirtió en símbolo de fortaleza dentro de su clan y le otorgó el respeto de otros líderes. Actualmente, Daizen dirige las fuerzas de combate acuático de Kirigakure. Su enfoque es simple: mantener a sus guerreros en constante entrenamiento y preparación. Cree que la debilidad es el mayor riesgo para la aldea. A pesar de su carácter severo, Daizen protege ferozmente a los civiles. Para él, el poder solo tiene valor si se utiliza para defender a los demás..', 'Tokubetsu Jounin', 14),
('haruna-yuki', 'Haruna Yuki', 'Yuki', 'Kiri', 'Líder del Clan Yuki', '“El hielo no solo congela; también preserva lo que vale la pena.”', '44', 'Haruna Yuki es la principal defensora de las regiones más frías y vulnerables de Kirigakure. Desde joven aprendió a utilizar su control del hielo para proteger asentamientos contra tormentas y deslizamientos. Su habilidad para mantener la calma en situaciones críticas la convirtió en una líder natural. Durante una tormenta devastadora, Haruna creó barreras de hielo que evitaron que una aldea costera fuera destruida por una inundación. Este acto salvó cientos de vidas y consolidó su reputación como protectora de la población. En la actualidad, Haruna dirige los sistemas de refugios y defensa climática de Kirigakure. También coordina evacuaciones durante desastres naturales y supervisa el almacenamiento de alimentos en condiciones extremas. Haruna cree que la verdadera fuerza se encuentra en la capacidad de proteger a otros. Su liderazgo se basa en la resiliencia y la responsabilidad.', 'Jounin', 13),
('masato-heizu', 'Masato Heizu', 'Heizu', 'Kiri', 'Líder del Clan Heizu', '“La niebla oculta el miedo, pero revela la estrategia.”', '50', 'Masato Heizu es uno de los líderes más influyentes en la política interna de Kirigakure. Nació en una familia dedicada a la navegación y la exploración en condiciones de baja visibilidad. Desde joven demostró una mente estratégica y una habilidad excepcional para planificar rutas y operaciones. Durante un conflicto territorial entre clanes, Masato actuó como mediador y logró evitar un enfrentamiento armado. Su capacidad para negociar acuerdos lo convirtió en una figura clave para mantener la estabilidad de la aldea. Actualmente, Masato dirige las operaciones de inteligencia y comunicación de Kirigakure. Su clan es responsable de guiar caravanas y coordinar movimientos militares en condiciones de niebla. Masato cree que la unidad es la mayor fortaleza de la aldea. Para él, la división interna representa el mayor peligro para el futuro de Kirigakure.', 'Tokubetsu Jounin', 14),
('raizen-kaguya', 'Raizen Kaguya', 'Kaguya', 'Kiri', 'Líder del Clan Kaguya – Director de la Prisión Marina Kotō Kangokutō', '“La fuerza no se hereda; se demuestra en cada batalla.”', '45', 'Raizen Kaguya es el comandante de las fuerzas terrestres de Kirigakure y uno de los guerreros más temidos de la aldea. Creció en una cultura donde el combate físico era parte de la vida diaria. Desde joven entrenó en resistencia extrema y disciplina militar. Durante una incursión enemiga, Raizen lideró una defensa que evitó la caída de un asentamiento estratégico. Su capacidad para resistir bajo presión lo convirtió en símbolo de fortaleza para su clan. En la actualidad, Raizen supervisa el entrenamiento militar de las unidades terrestres y mantiene protocolos de defensa para emergencias. Su prioridad es garantizar que la aldea esté preparada para cualquier ataque. Raizen cree que la seguridad se construye con disciplina. Para él, la fuerza es una herramienta necesaria para preservar la paz.', 'Equivalente a ANBU', 15),
('ren-hozuki', 'Ren Hozuki', 'Hozuki', 'Kiri', 'Líder del Clan Hozuki', '“La flexibilidad es la verdadera fortaleza.”', '46', 'Desde joven, Ren demostró un talento excepcional para adaptar sus habilidades líquidas a diferentes situaciones de combate y supervivencia. Su enfoque estratégico lo llevó a desarrollar tácticas flexibles que permitieron al clan responder rápidamente a emergencias. Esta capacidad de adaptación se convirtió en la base de su liderazgo. Como líder, Ren promueve la innovación y la colaboración entre clanes. Ha impulsado la creación de patrullas conjuntas y sistemas de defensa coordinados, fortaleciendo la seguridad colectiva de Kirigakure. Su visión se centra en construir una aldea resiliente capaz de enfrentar desafíos inesperados. Ren cree que la rigidez conduce al fracaso. Para él, la verdadera fortaleza radica en la capacidad de cambiar y evolucionar. Su liderazgo ha transformado al clan Hozuki en un símbolo de adaptabilidad y cooperación dentro de la aldea.', 'Jounin', 13),
('kaede-terumi', 'Kaede Terumi', 'Terumi', 'Kiri', 'Líder del Clan Terumi', '“El conocimiento salva más vidas que la espada.”', '43', 'Kaede Terumi creció en un entorno donde la ciencia y la medicina eran tan importantes como el combate. Desde joven mostró interés por el estudio de técnicas basadas en vapor y calor, así como en la purificación de agua y el tratamiento de enfermedades. Estas habilidades se volvieron esenciales durante periodos de crisis sanitaria en la aldea. Durante el gran desastre natural que azotó la isla, Kaede lideró operaciones de rescate y desarrolló métodos para purificar agua contaminada, evitando la propagación de enfermedades. Su trabajo salvó innumerables vidas y elevó el prestigio del clan como protectores de la salud pública. Como líder, Kaede ha impulsado la creación de sistemas de saneamiento comunitario y programas de formación médica para jóvenes shinobi. Su enfoque combina conocimiento científico y responsabilidad social, fortaleciendo la resiliencia de la población. Kaede cree que la verdadera fortaleza de una aldea no se mide por su poder militar, sino por su capacidad para cuidar a su gente. Bajo su liderazgo, el clan Terumi se ha convertido en el principal centro médico y científico de Kirigakure.', 'Equivalente a Jounin', 13),
('shigure-kodon', 'Shigure Kodon', 'Kodon', 'Kiri', 'Líder del Clan Kodon', '“Toda sustancia puede ser veneno o medicina; la diferencia está en la sabiduría.”', '51', 'Shigure Kodon nació en un clan tradicionalmente aislado, dedicado al estudio de toxinas y compuestos químicos. Desde joven aprendió a identificar plantas venenosas y a desarrollar antídotos, habilidades que eran esenciales para la supervivencia en territorios peligrosos. Su talento científico lo convirtió en uno de los investigadores más respetados de su generación. Como líder, Shigure ha transformado el conocimiento del clan en una herramienta para la protección de la aldea. Ha establecido laboratorios y centros de investigación donde se desarrollan antídotos, medicinas y sustancias defensivas. Su objetivo es garantizar que Kirigakure esté preparada para enfrentar amenazas biológicas y ambientales. Shigure cree que el conocimiento es la forma más poderosa de defensa. Bajo su liderazgo, el clan Kodon ha pasado de ser un grupo aislado a convertirse en uno de los pilares científicos y médicos de la aldea.', 'Tokubetsu Jounin', 14);

-- NPCs secundarios de Kirigakure (personal operativo). Sin frase.
INSERT INTO `mybb_sg_sg_npcs` (`codigo`, `nombre`, `clan_grupo`, `afiliacion`, `cargo`, `frase`, `edad`, `descripcion`, `rango`, `nivel`) VALUES
('isamu-funato', 'Isamu Funato', 'Funato', 'Kiri', 'Capitán de Patrulla Costera', '', '46', 'Isamu dirige las patrullas marítimas que vigilan las rutas comerciales y los accesos a la isla. Es un navegante experimentado que ha sobrevivido a tormentas y ataques de criaturas marinas. Su principal responsabilidad es detectar amenazas antes de que lleguen a la costa. Es respetado por su capacidad para mantener la disciplina bajo presión.', 'Jounin', 13),
('kaito-hoshigaki', 'Kaito Hoshigaki', 'Hoshigaki', 'Kiri', 'Instructor de Combate Acuático', '', '38', 'Kaito entrena a nuevos reclutas en técnicas de combate bajo el agua. Es exigente y directo, pero profundamente comprometido con la seguridad de sus estudiantes. Cree que la preparación física es la base de la supervivencia. Su reputación como instructor lo ha convertido en figura clave en la formación militar.', 'Chunnin', 11),
('miyu-yuki', 'Miyu Yuki', 'Yuki', 'Kiri', 'Coordinadora de Refugios Climáticos', '', '34', 'Miyu supervisa la construcción y mantenimiento de refugios utilizados durante tormentas o inundaciones. Su trabajo ha salvado numerosas vidas en situaciones de emergencia. Es conocida por su calma y su capacidad para tomar decisiones rápidas. Considera que la prevención es la mejor forma de protección.', 'Equivalente a Chunnin', 8),
('takeda-heizu', 'Takeda Heizu', 'Heizu', 'Kiri', 'Navegador de Rutas en Niebla', '', '41', 'Takeda es responsable de guiar caravanas y embarcaciones en condiciones de baja visibilidad. Su conocimiento del terreno y del clima lo convierte en un recurso esencial para el comercio y la seguridad. Es meticuloso y paciente, cualidades necesarias para su profesión. Muchos lo consideran el mejor guía de la aldea.', 'Equivalente a Chunnin', 9),
('juro-kaguya', 'Juro Kaguya', 'Kaguya', 'Kiri', 'Comandante de Defensa Terrestre', '', '44', 'Juro lidera unidades encargadas de proteger los accesos terrestres a la aldea. Su estilo de liderazgo es directo y disciplinado. Ha participado en múltiples operaciones de defensa y rescate. Es conocido por exigir el máximo esfuerzo de sus soldados.', 'Jounin', 12),
('aiko-hozuki', 'Aiko Hozuki', 'Hozuki', 'Kiri', 'Ingeniera Hidráulica', '', '36', 'Aiko diseña sistemas de drenaje y control de inundaciones dentro de la aldea. Su trabajo es fundamental para evitar desastres durante tormentas intensas. Es creativa y persistente, siempre buscando soluciones innovadoras. Cree que la infraestructura es la primera línea de defensa contra la naturaleza.', 'Equivalente a Chunnin', 8),
('rin-terumi', 'Rin Terumi', 'Terumi', 'Kiri', 'Médica de Emergencias', '', '33', 'Rin trabaja en el hospital central de Kirigakure, atendiendo heridos en situaciones críticas. Su capacidad para mantener la calma en medio del caos la convierte en una profesional indispensable. Ha participado en numerosas misiones de rescate. Es conocida por su dedicación absoluta a sus pacientes.', 'Chunnin', 9),
('shun-kodon', 'Shun Kodon', 'Kodon', 'Kiri', 'Investigador de Sustancias Tóxicas', '', '40', 'Shun desarrolla antídotos y compuestos defensivos para proteger a la población. Su laboratorio es uno de los más importantes de la aldea. Es reservado y extremadamente meticuloso en su trabajo. Considera que el conocimiento científico es la mejor herramienta de defensa.', 'Equivalente a Chunnin', 9),
('haruto-funato', 'Haruto Funato', 'Funato', 'Kiri', 'Constructor de Embarcaciones', '', '52', 'Haruto supervisa la construcción y reparación de barcos utilizados por la aldea. Su experiencia garantiza que las embarcaciones sean resistentes a condiciones extremas. Es paciente y perfeccionista en cada detalle. Muchos marineros confían en su habilidad para mantener sus naves seguras.', 'Equivalente a Chunnin', 8),
('sora-hoshigaki', 'Sora Hoshigaki', 'Hoshigaki', 'Kiri', 'Exploradora Submarina', '', '29', 'Sora se especializa en explorar cavernas y rutas submarinas. Su trabajo permite descubrir recursos y detectar amenazas ocultas. Es valiente y curiosa, siempre dispuesta a asumir riesgos calculados. Su conocimiento del océano la convierte en una pieza clave para la seguridad de la aldea.', 'Chunnin', 7),
('naoki-yuki', 'Naoki Yuki', 'Yuki', 'Kiri', 'Guardián de Almacenes de Hielo', '', '47', 'Naoki administra depósitos donde se conservan alimentos y medicinas en condiciones frías. Su labor asegura el abastecimiento durante emergencias. Es disciplinado y organizado, cualidades esenciales para su responsabilidad. Cree que la estabilidad de la aldea depende de la preparación.', 'Equivalente a Chunnin', 8),
('hikari-heizu', 'Hikari Heizu', 'Heizu', 'Kiri', 'Mensajera Estratégica', '', '31', 'Hikari transporta información confidencial entre unidades militares y líderes de la aldea. Su velocidad y discreción la convierten en una mensajera confiable. Ha completado misiones en condiciones extremadamente peligrosas. Su lealtad es incuestionable.', 'Chunnin', 7),
('kenji-kaguya', 'Kenji Kaguya', 'Kaguya', 'Kiri', 'Instructor de Reclutas', '', '42', 'Kenji entrena a nuevos combatientes en técnicas básicas de defensa y resistencia física. Es estricto pero justo con sus estudiantes. Cree que la disciplina es la base de cualquier guerrero. Su experiencia lo convierte en uno de los instructores más respetados de la aldea.', 'Chunnin', 10),
('mizuki-hozuki', 'Mizuki Hozuki', 'Hozuki', 'Kiri', 'Operadora de Evacuación', '', '35', 'Mizuki coordina la evacuación de civiles durante emergencias. Su rapidez para organizar movimientos masivos ha salvado numerosas vidas. Es eficiente y decidida en situaciones críticas. Considera que proteger a la población es la misión más importante.', 'Equivalente a Chunnin', 8),
('daichi-terumi', 'Daichi Terumi', 'Terumi', 'Kiri', 'Supervisor de Saneamiento', '', '48', 'Daichi dirige equipos encargados de mantener el agua potable y las condiciones sanitarias de la aldea. Su trabajo previene enfermedades y crisis de salud pública. Es metódico y responsable en cada tarea. Cree que la salud colectiva es la base de la supervivencia.', 'Equivalente a Chunnin', 8),
('ryo-funato', 'Ryo Funato', 'Funato', 'Kiri', 'Supervisor de Faros Marítimos', '', '49', 'Ryo es responsable de mantener operativos los faros que guían a las embarcaciones durante tormentas y noches de baja visibilidad. Su trabajo reduce accidentes y facilita el regreso seguro de las flotas. Es meticuloso y paciente, acostumbrado a largas horas de vigilancia en condiciones extremas. Cree que una luz encendida en el momento correcto puede salvar más vidas que una espada.', 'Equivalente a Chunnin', 7),
('kenshin-hoshigaki', 'Kenshin Hoshigaki', 'Hoshigaki', 'Kiri', 'Guardián del Puerto Profundo', '', '37', 'Kenshin vigila la entrada principal al puerto submarino de Kirigakure, una zona estratégica donde se concentran recursos y embarcaciones. Su fuerza física y su resistencia lo convierten en un defensor confiable en situaciones críticas. Ha participado en múltiples operaciones de rescate y defensa. Considera que su puesto es la primera barrera contra cualquier amenaza proveniente del océano.', 'Chunnin', 10),
('ayame-yuki', 'Ayame Yuki', 'Yuki', 'Kiri', 'Cartógrafa Climática', '', '32', 'Ayame registra patrones de tormentas, corrientes y cambios de temperatura para anticipar fenómenos peligrosos. Sus mapas permiten planificar rutas seguras y evacuaciones tempranas. Es analítica y observadora, con gran atención al detalle. Cree que comprender la naturaleza es la mejor forma de proteger a la población.', 'Equivalente a Chunnin', 8),
('toru-heizu', 'Toru Heizu', 'Heizu', 'Kiri', 'Coordinador de Señales de Niebla', '', '45', 'Toru administra las torres de señalización que permiten la comunicación entre distritos cuando la visibilidad es limitada. Su sistema de señales ha evitado colisiones y confusiones durante emergencias. Es organizado y confiable, conocido por su capacidad para reaccionar rápidamente ante cambios inesperados. Considera que la comunicación clara es esencial para la seguridad de la aldea.', 'Equivalente a Chunnin', 9),
('renji-kaguya', 'Renji Kaguya', 'Kaguya', 'Kiri', 'Capitán de Guardia de Frontera', '', '43', 'Renji lidera unidades encargadas de proteger las rutas terrestres que conectan Kirigakure con asentamientos exteriores. Su estilo de mando es firme y disciplinado, enfocado en la prevención de conflictos. Ha repelido múltiples incursiones hostiles sin causar bajas innecesarias. Cree que la vigilancia constante es la clave para mantener la paz.', 'Jounin', 12);

-- Espadachines de la Niebla (sin cargo ni frase; se ignora el campo Espada).
-- Nota: Raizen Kaguya, Ren Hozuki y Shigure Kodon se omiten porque ya están cargados como líderes de clan.
INSERT INTO `mybb_sg_sg_npcs` (`codigo`, `nombre`, `clan_grupo`, `afiliacion`, `cargo`, `frase`, `edad`, `descripcion`, `rango`, `nivel`) VALUES
('takeshi-funato', 'Takeshi Funato', 'Funato', 'Kiri', 'Espadachín de la Niebla', '', '41', 'Takeshi es el ejecutor principal de las fuerzas navales de Kirigakure y el líder actual de los 7 Espadachines. Su estilo de combate es directo, brutal y decisivo, diseñado para terminar enfrentamientos rápidamente. Es conocido por liderar operaciones de intercepción en mar abierto y por su capacidad para mantener la calma en medio del caos. Su reputación como combatiente implacable lo ha convertido en símbolo de disciplina dentro de la aldea.', 'ANBU', 15),
('daigo-hoshigaki', 'Daigo Hoshigaki', 'Hoshigaki', 'Kiri', 'Espadachín de la Niebla', '', '39', 'Daigo es uno de los combatientes más temidos de Kirigakure. Su resistencia física y su agresividad natural lo convierten en una fuerza devastadora en combate prolongado. Es especialista en enfrentamientos acuáticos y suele ser desplegado en misiones de alto riesgo. A pesar de su apariencia intimidante, protege ferozmente a sus compañeros y demuestra una lealtad absoluta hacia la aldea.', 'Tokubetsu Jounin', 14),
('reina-yuki', 'Reina Yuki', 'Yuki', 'Kiri', 'Espadachín de la Niebla', '', '36', 'Reina es la estratega defensiva del grupo y una combatiente extremadamente precisa. Prefiere analizar el campo de batalla antes de actuar, utilizando su espada para controlar el flujo del combate. Ha salvado numerosas vidas durante evacuaciones y operaciones de rescate. Su presencia aporta equilibrio y estabilidad emocional al equipo.', 'Jounin', 13),
('masaru-heizu', 'Masaru Heizu', 'Heizu', 'Kiri', 'Espadachín de la Niebla', '', '43', 'Masaru es el especialista en infiltración y combate táctico. Utiliza la velocidad y la sorpresa como sus principales armas, coordinando ataques rápidos y precisos. Es responsable de planificar operaciones secretas y misiones de reconocimiento. Su mente estratégica lo convierte en uno de los miembros más valiosos del escuadrón.', 'Jounin', 13);
